//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfGameApp.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IWcfService")]
    public interface IWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/Register", ReplyAction="http://tempuri.org/IWcfService/RegisterResponse")]
        bool Register(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/Heartbeat", ReplyAction="http://tempuri.org/IWcfService/HeartbeatResponse")]
        bool Heartbeat();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/Unregister", ReplyAction="http://tempuri.org/IWcfService/UnregisterResponse")]
        bool Unregister(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceChannel : WpfGameApp.Services.IWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceClient : System.ServiceModel.ClientBase<WpfGameApp.Services.IWcfService>, WpfGameApp.Services.IWcfService {
        
        public WcfServiceClient() {
        }
        
        public WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Register(string name) {
            return base.Channel.Register(name);
        }
        
        public bool Heartbeat() {
            return base.Channel.Heartbeat();
        }
        
        public bool Unregister(string name) {
            return base.Channel.Unregister(name);
        }
    }
}
